name: Build Docker Container and Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: Aleksbogdanov12/django-k8s-web1/.github/workflows/main.yml@main
  docker-build:
    runs-on: ubuntu-latest # operating system your code will run on
    needs: [test_django_job]
    env:
      CLUSTER_NAME: django-k8s
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}
      - name: Login to DO Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build Container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/cfe-django-k8s/web:latest \
            -t registry.digitalocean.com/cfe-django-k8s/web:${GITHUB_SHA::7} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/cfe-django-k8s/web --all-tags
      - name: K8s cluster kubeconfig file short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update secrets
        run: |
          cat << EOF >> web/.env.prod
          DJANGO_SUPERUSER_USERNAME=admin
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} 
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} 
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}  
          ENV_ALLOWD_HOST=${{ secrets.ENV_ALLOWD_HOST }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=2${{ secrets.POSTGRES_PORT }}
          EOF
          kubectl delete secret django-k8s-web-prod-env
          kubectl create secret generic django-k8s-web-prod-env --from-env-file=web/.env.prod

      - name: Update Deployment image
        run: |
          kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/cfe-django-k8s/web:${GITHUB_SHA::7}
      - name: Wait for Rollout to finish
        run: |
          kubectl rollout status deployment/django-k8s-web-deployment
      - name: Migrate Database
        run: |
          export SINGLE_RUNNING_POD=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_RUNNING_POD -- bash /app/migrate.sh




