name: Deploy to Digital Ocean

on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      - run: cd /home/runner/work/django-k8s-web1/django-k8s-web1/web
      - run: pip install -r requirements.txt
      - run: python manage.py test    
  build_image:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd /home/runner/work/django-k8s-web1/django-k8s-web1/web
          docker build -t registry.digitalocean.com/cfe-django-k8s/web:v1 -f Dockerfile .

