name: Deploy to Digital Ocean

on: [push, pull]

jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt 
      - run: python manage.py test    
  build_image:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2